#!/bin/sh
set -e

# Faster key response
defaults write -g KeyRepeat -int 2
defaults write -g InitialKeyRepeat -int 12

# Enable audio codec
sudo defaults write bluetoothaudiod "Enable AptX codec" -bool true
sudo defaults write bluetoothaudiod "Enable AAC codec" -bool true

# Show hidden files
defaults write com.apple.finder AppleShowAllFiles YES

# Open apps from 3rd-party developers
sudo defaults write /Library/Preferences/com.apple.security GKAutoRearm -bool NO

# Change screenshot position
defaults write com.apple.screencapture location -string '~/Desktop/Screenshots'

# Set Dock position
defaults write com.apple.Dock orientation -string bottom
defaults write com.apple.Dock autohide -bool true
defaults write com.apple.Dock show-process-indicators -bool false

# Hide menu bar
defaults write NSGlobalDomain _HIHideMenuBar -bool true

# Restart things
killall Dock
killall SystemUIServer
